[package]
name = "journald-broker"
version = "0.1.0"

authors = ["Bhanupong Petchlert <bpetlert@gmail.com>"]

description = "An event broker daemon for journald"
documentation = "https://github.com/bpetlert/journald-broker"
homepage = "https://github.com/bpetlert/journald-broker"
license = "MIT"
readme = "README.adoc"
repository = "https://github.com/bpetlert/journald-broker"

edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.18", features = ["derive"] }
config = { version = "0.13.2", default-features = false, features = ["toml"] }
humantime-serde = "1.1.1"
mimalloc = "0.1.30"
once_cell = "1.16.0"
regex = "1.6.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
strum = { version = "0.24.1", features = ["derive"] }
systemd = { version = "0.10.0", default-features = false, features = [
    "journal",
] }
tracing = { version = "0.1.37", features = [
    "max_level_debug",
    "release_max_level_debug",
] }
tracing-subscriber = { version = "0.3.16", default-features = false, features = [
    "env-filter",
    "fmt",
] }
wait-timeout = "0.2.0"
