[global]
## Filter log message using journal fields. This setting is optional. Default value is no filter.
## See https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#User%20Journal%20Fields for more details.
filters = ["_TRANSPORT=kernel", "PRIORITY=4"]

## Run a script with a timeout specified (in seconds). Default is 20 seconds.
# script_timeout = "20"

## [events.<EVENT_NAME>]
# [events.event-1]
## Filter log message using regular expression. The value is surrounded by single quotes.
# message = 'some regex'
#
## Delay before next checking log message. Default is zero.
## e.g.
##     1 hour 1 minute 1 second
##     5s
##     5 minute
##     5m
# next-watch-delay = ""
#
## Script to run when message is found.
# script = "/path/to/script"
#
## Wait for current script to finish before run next script. Default is true.
# script-wait = true

[events.xhci_hcd-error]
message = 'xhci_hcd 0000:04:00\.0: WARN waiting for error on ep to be cleared'
next-watch-delay = "5 minute"
script = "/usr/local/bin/xhci_hcd-rebind.sh"
