= journald-broker
:toc:
:toc-placement!:
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

image:https://img.shields.io/github/v/tag/bpetlert/journald-broker?include_prereleases&label=release&style=flat-square[Release,link=https://github.com/bpetlert/journald-broker/releases/latest]
image:https://img.shields.io/aur/version/journald-broker?style=flat-square["AUR: journald-broker",link=https://aur.archlinux.org/packages/journald-broker/]
image:https://img.shields.io/github/license/bpetlert/journald-broker?style=flat-square["License: GPL-3.0-or-later",link=./COPYING]

*journald-broker* is a log-based event dispatcher daemon for systemd's journal.
The events are defined by user.
An event is generated by parsing log entries using a given regular expression.
Each event has a script attached to it, which is executed when the event is fired.

toc::[]

== Installation

=== Arch Linux

*journald-broker* can be installed from https://aur.archlinux.org/packages/journald-broker[AUR].
To build and install arch package from GIT source, try:

[source,console]
$ git clone https://github.com/bpetlert/journald-broker.git
$ cd journald-broker
$ makepkg -p PKGBUILD.local
$ pacman -U journald-broker-x.x.x.rx.gxxxxxxx-1-x86_64.pkg.tar.zst

Then enable/start `journald-broker.service`

[source,console]
$ systemctl enable --now journald-broker.service

== Usage

The configuration file is located in `/etc/systemd/journald-broker.toml`.
User is allowed to define event as many times as needed.
Each event must has a unique name.
A script for each event must be a regular executable file owned by root.

./etc/systemd/journald-broker.toml
[source,toml]
----
# [global]
## Filter log message using journal fields. This setting is optional. Default value is no filter.
## See https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#User%20Journal%20Fields for more details.
# filters = ["_TRANSPORT=kernel", "PRIORITY=4"]

## Run a script with a timeout specified (in seconds). Default is 20 seconds.
# script_timeout = "20"

## [events.<EVENT_NAME>]
# [events.event-1]
## Filter log message using regular expression. The value is surrounded by single quotes.
# message = 'some regex'
#
## Delay before next checking log message. Default is zero.
## e.g.
##     1 hour 1 minute 1 second
##     5s
##     5 minute
##     5m
# next-watch-delay = ""
#
## Script to run when message is found.
# script = "/path/to/script"
#
## Wait for current script to finish before run next script. Default is true.
# script-wait = true
----

When an event is dispatched, the related information is passed to its script using environment variables below:

|===
| Environment Variable | Description

| `JNB_MESSAGE`
| Error log message

| `JNB_JSON`
| Full journal log entry, encoded in JSON format.
|===

=== Example 1: Extract a specific log to file

This example shows how to extract log message that start start with "xhci_hcd 0000:04:00.0: WARN".
Then write log entry to external file.

./etc/systemd/journald-broker.toml
[source,toml]
----
[events.extract-xhci_hcd-error]
message = 'xhci_hcd 0000:04:00\.0: WARN.*'
script = "/usr/local/bin/extract-xhci_hcd-error.sh"
----

./usr/local/bin/extract-xhci_hcd-error.sh
[source,bash]
----
#!/usr/bin/env bash

echo ${JNB_JSON} >> /path/to/log/file

exit 0
----

=== Example 2: Workaround error of xhci_hcd when connect to USB-3.0-to-Ethernet

The "USB 3.0 to ethernet adapter" device on xhci_hcd bus will sometime stop functioning until reconnect or rebind.
The error will show in journal log as show below:

[source,console]
----
[ 1179.475926] kernel: xhci_hcd 0000:04:00.0: WARN: TRB error for slot 1 ep 5 on endpoint
[ 1179.607026] kernel: xhci_hcd 0000:04:00.0: WARN waiting for error on ep to be cleared
[ 1179.607049] kernel: xhci_hcd 0000:04:00.0: WARN waiting for error on ep to be cleared
[ 1179.607054] kernel: xhci_hcd 0000:04:00.0: WARN waiting for error on ep to be cleared
[ 1179.607058] kernel: xhci_hcd 0000:04:00.0: WARN waiting for error on ep to be cleared
----

In this example, `journald-broker` will monitor only the warning message (`PRIORITY=4`) of kernel log (`_TRANSPORT=kernel`).
After the these error messages are found, it will automatically rebind the device.
Since the log message will repeat really fast, the event will be fired repeatedly and attempt to rebind the device again.
It would be undesirable result.
To prevent this, it is necessary to slow down for firing the same event by using `next-watch-delay` setting.

./etc/systemd/journald-broker.toml
[source,toml]
----
[global]
filters = ["_TRANSPORT=kernel", "PRIORITY=4"]

[events.xhci_hcd-error]
message = 'xhci_hcd 0000:04:00\.0: WARN waiting for error on ep to be cleared'
next-watch-delay = "1 minute"
script = "/usr/local/bin/xhci_hcd-rebind.sh"
----

./usr/local/bin/xhci_hcd-rebind.sh
[source,bash]
----
#!/usr/bin/env bash

# Record system info (in JSON format) to journal
sys_info="
{
  \"ErrorLog\": \"${JNB_MESSAGE}\",
  \"SysInfo\": [
    \"$(uname --kernel-name)-$(uname --kernel-release)-$(uname --machine) $(uname --kernel-version)\",
    \"$(pacman -Qi asix-ax88179-dkms | grep Version | awk '{ print "asix-ax88179-dkms-"$3 }')\" ]
}"
echo $sys_info | /usr/bin/jq --compact-output --monochrome-output

# Disconnect device
echo "Unbind => ASIX Electronics Corp. AX88179 Gigabit Ethernet"
echo -n "0000:04:00.0" > /sys/bus/pci/drivers/xhci_hcd/unbind
sleep 3s

# Reconnect device
echo "Bind => ASIX Electronics Corp. AX88179 Gigabit Ethernet"
echo -n "0000:04:00.0" > /sys/bus/pci/drivers/xhci_hcd/bind

exit 0
----

== Design

[link=https://raw.githubusercontent.com/bpetlert/journald-broker/main/docs/assets/journald-broker.svg?sanitize=true&raw=true]
image::https://raw.githubusercontent.com/bpetlert/journald-broker/main/docs/assets/journald-broker.svg?sanitize=true&raw=true[Sequence Diagram]

== License

*link:./COPYING[GNU General Public License v3.0 or later]*
