name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.rs"
      - "**/Cargo.*"
      - ".github/workflows/rust.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.rs"
      - "**/Cargo.*"
      - ".github/workflows/rust.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: apt-get update
      run: sudo apt-get -o Acquire::Retries=3 update
    - name: Install libsystemd-dev
      run: sudo apt-get -o Acquire::Retries=3 install libsystemd-dev

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
